# Generated by Django 6.0 on 2025-12-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('price', models.PositiveIntegerField(unique=True, verbose_name='price')),
                ('image', models.FileField(null=True, upload_to='images')),
            ],
        ),
    ]
