# Generated by Django 6.0 on 2025-12-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makeup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Custmor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=12, unique=True)),
                ('password', models.TextField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Makeup.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Makeup.products')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='custmor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Makeup.custmor'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.BigIntegerField(max_length=4, verbose_name='total_price')),
                ('custmor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Makeup.custmor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Makeup.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Makeup.products')),
            ],
        ),
    ]
